#:schema ./.aviutl2-cli/aviutl2.schema.json

[project]
id = "sevenc-nanashi.anarchy_time_control_editor-aux2"
name = "anarchy_time_control_editor.aux2"
version = "0.1.0"

[artifacts.anarchy-time-control-editor-aux2]
destination = "Plugin/anarchy_time_control_editor.aux2"

[artifacts.anarchy-time-control-editor-aux2.profiles.debug]
source = "target/debug/anarchy_time_control_editor_aux2.dll"
build = "cargo build"

[artifacts.anarchy-time-control-editor-aux2.profiles.release]
source = "target/release/anarchy_time_control_editor_aux2.dll"
build = "cargo build --release"

[artifacts.anarchy-time-control-editor-aux2-english]
destination = "Language/English.anarchy_time_control_editor-aux2.aul2"
source = "i18n/English.aul2"

[development]
aviutl2_version = "latest"
