[package]
name = "anarchy_time_control_editor-aux2"
version = "0.1.0-preview.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.104"
aviutl2 = "0.45.0"
aviutl2-eframe = "0.45.0"
aviutl2_track_parser = { git = "https://github.com/sevenc-nanashi/aviutl2_track_parser", version = "0.1.0" }
tap = "1.0.1"
tracing = "0.1.44"
xxhash-rust = { version = "0.8.18", features = ["xxh32"] }
